# Runs the code from docker image and push updates to repo and channel
name: Runner
on:
  push:
  schedule:
    - cron: "5,20,35,50 5-20 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    container:
      image: vikmind/tgn-water:latest
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CHANNEL: ${{ secrets.CHANNEL }}
        ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
        INFO_SCRIPT: 'getWaterInfo.js'
        DATA_DIR: '/data/'
      volumes:
        - data:/data
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run
        run: npm start
        with:
          entrypoint: /bin/bash
      # -
      #   name: Commit and push if changed
      #   run: |-
      #       git config user.name "Automated"
      #       git config user.email "actions@users.noreply.github.com"
      #       git add -A
      #       timestamp=$(date --rfc-3339=seconds --utc)
      #       git commit -m "Latest data: ${timestamp}" || exit 0
      #       git push
