# Runs the code from docker image and push updates to repo and channel
name: Runner
on:
  workflow_dispatch:
  schedule:
    - cron: "5,20,35,50 5-20 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Hello
        run: echo "Hello from actions"
      -
        name: List
        run: ls -al

